apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  #namespace: {{ .Values.settings.env }}
  labels:
    app.kubernetes.io/name: {{ .Values.settings.name }}
    app.kubernetes.io/part-of: {{ .Values.settings.name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  app-name: {{ .Values.settings.name }}
  app-env: {{ .Values.settings.env }}
  node-env: {{ .Values.settings.nodeEnv }}
  domain: {{ .Values.settings.domain }}
  version: {{ .Values.settings.version }}

  server-url: {{ printf "https://%s/backend" .Values.settings.domain }}
  client-url: {{ printf "https://%s" .Values.settings.domain }}
  graphql-uri: {{ printf "https://%s/backend/graphql" .Values.settings.domain }}

  mail: {{ .Values.mail.type }}
  mail-from-name: {{ .Values.mail.from.name }}
  mail-from-email: {{ .Values.mail.from.email }}
  mail-host: {{ .Values.mail.smtp.host }}
  mail-port: {{ .Values.mail.smtp.port | quote }}
