version: '3.9' # optional since v1.27.0
services:
    postgres:
        image: postgres:14.5
        ports:
            - 5432:5432
        volumes:
            - dbvolume:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=secret
            - PGDATA=/var/lib/postgresql/data/pgdata
    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - 1080:1080
            - 1025:1025

volumes:
    dbvolume: {}
